name: Sulmuro-BE CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # 1. 프로젝트 폴더로 이동
            cd ~/2025-hackerthon-7-sulmuro-backend
            
            # 2. 외부 설정 파일(application-prod.properties) 생성
            # application.yml의 설정 키 이름을 그대로 사용합니다.
            echo "spring.datasource.url=${{ secrets.DB_URL }}" > application-prod.properties
            echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> application-prod.properties
            echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> application-prod.properties
            echo "gemini.api-key=${{ secrets.GEMINI_API_KEY }}" >> application-prod.properties
            echo "naver.api.client-id=${{ secrets.NAVER_API_CLIENT_ID }}" >> application-prod.properties
            echo "naver.api.client-secret=${{ secrets.NAVER_API_CLIENT_SECRET }}" >> application-prod.properties
            echo "deepl.authKey=${{ secrets.DEEPL_AUTH_KEY }}" >> application-prod.properties
            # 3. 배포 스크립트 실행
            ./deploy.sh